export default {
  docusaurusSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  algoliaDocsearchSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  ionicSidebar: [
    {
      type: "autogenerated",
      dirName: ".",
    },
  ],
  // htmlSidebar: [
  //   {
  //     type: "autogenerated",
  //     dirName: ".",
  //   },
  // ],

  // cssSidebar: [
  //   {
  //     type: "autogenerated",
  //     dirName: ".",
  //   },
  // ],

  // jsSidebar: [
  //   {
  //     type: "autogenerated",
  //     dirName: ".",
  //   },
  // ],
}
